---
title: "Single Site"
vignette: >
  %\VignetteIndexEntry{single}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: rmarkdown::html_vignette
---

```{r, include=FALSE}
knitr::opts_chunk$set(eval = TRUE)
```

Load the depression data into R.

```{r}
file <- "https://github.com/celehs/KESER/raw/master/rdata/depression.rds"
data <- readRDS(url(file, "rb"))
```

Feature Selection with Embeddings from Partners Healthcare 

```{r}
library(KESER)
system.time(loc.fit.RPDR <- loc.feature.selection(
  data$X_full_lst[[1]], data$Y_full_lst[[1]],
  data$X_train_lst[[1]], data$Y_train_lst[[1]], 
  data$X_valid_lst[[1]], data$Y_valid_lst[[1]],
  alpha = 1, lambda_lst = NULL, up_rate = 10, 
  drop_rate = 0.5, cos_cut = 0.1, add.ridge = TRUE))
loc.fit.RPDR
```

Feature Selection with Embeddings from Veteran Affairs (VA)

```{r}
library(KESER)
system.time(loc.fit.VA <- loc.feature.selection(
  data$X_full_lst[[2]], data$Y_full_lst[[2]],
  data$X_train_lst[[2]], data$Y_train_lst[[2]], 
  data$X_valid_lst[[2]], data$Y_valid_lst[[2]],
  alpha = 1, lambda_lst = NULL, up_rate = 10, 
  drop_rate = 0.5, cos_cut = 0.1, add.ridge = TRUE))
loc.fit.VA
```
