---
output: html_document
---

```{r}
# remotes::install_github("celehs/KESER")
library(KESER)
library(data.table)
```

```{r}
file <- "https://github.com/celehs/KESER/raw/master/rdata/depression.rds"
data <- readRDS(url(file, "rb"))
```

```{r}
system.time(up_rate_1 <- int.feature.selection(
  data$X_full_lst, data$Y_full_lst, 
  data$X_train_lst, data$Y_train_lst, 
  data$X_valid_lst, data$Y_valid_lst,
  lambda_lst = NULL, add.ridge = TRUE))
fwrite(up_rate_1$results, "up_rate_1.csv")
up_rate_1
```

```{r}
system.time(up_rate_2 <- int.feature.selection(
  data$X_full_lst, data$Y_full_lst, 
  data$X_train_lst, data$Y_train_lst, 
  data$X_valid_lst, data$Y_valid_lst,
  lambda_lst = NULL, add.ridge = TRUE, up_rate = 2))
fwrite(up_rate_2$results, "up_rate_2.csv")
up_rate_2
```

```{r}
system.time(up_rate_4 <- int.feature.selection(
  data$X_full_lst, data$Y_full_lst, 
  data$X_train_lst, data$Y_train_lst, 
  data$X_valid_lst, data$Y_valid_lst,
  lambda_lst = NULL, add.ridge = TRUE, up_rate = 4))
fwrite(up_rate_4$results, "up_rate_4.csv")
up_rate_4
```

```{r}
system.time(up_rate_8 <- int.feature.selection(
  data$X_full_lst, data$Y_full_lst, 
  data$X_train_lst, data$Y_train_lst, 
  data$X_valid_lst, data$Y_valid_lst,
  lambda_lst = NULL, add.ridge = TRUE, up_rate = 8))
fwrite(up_rate_8$results, "up_rate_8.csv")
up_rate_8
```
